services:
  db:
    image: postgres:13
    volumes:
      - db_lumina:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-lumina}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  server:
    image: 'lumina/api'
    build:
      context: api
    command: gunicorn run:app -w 2 --threads 2 -b 0.0.0.0:${SERVER_PORT:-5000}
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - ./api/.env
    depends_on:
      - db

  front:
    image: 'lumina/front'
    build:
      context: front
    command: npm run serve
    env_file:
      - ./front/.env
    ports:
      - ${FRONT_PORT:-8080}:8080

volumes:
  db_lumina:
