services:
  db:
    image: postgres:13
    volumes:
      - db_lumina:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-lumina}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  server:
    image: 'lumina/api'
    build:
      context: api
      cache_from:
        - 'lumina/api'
    command: flask run --host 0.0.0.0
    volumes:
      - ./api/app:/app
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - ./api/.env
    depends_on:
      - db

  front:
    image: 'lumina/front'
    build:
      context: front
      cache_from:
        - 'lumina/front'
    command: npm run serve
    volumes:
      - ./front:/front
    env_file:
      - ./front/.env
    ports:
      - ${FRONT_PORT:-8080}:8080

volumes:
  db_lumina:
