services:
  db_test:
    image: postgres:13
    volumes:
      - db_lumina_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_TEST_NAME:-lumina}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  server:
    image: 'lumina/api'
    build:
      context: .
      cache_from:
        - 'lumina/api'
    volumes:
      - ./app:/app
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - .env
    depends_on:
      - db_test

volumes:
  db_lumina_test:
