version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db_glados:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-glados}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  server:
    image: 'glados/api'
    build:
      context: .
      cache_from:
        - 'glados/api'
    command: gunicorn run:app -w 2 --threads 2 -b 0.0.0.0:${SERVER_PORT:-5000}
    volumes:
      - ./app:/app
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_glados:
